### ISSUE TITLE
Display UUID as string from a BINARY(16) column

### ISSUE THREAD

**Issue by kevindb** [Sequel-Ace/Sequel-Ace#348]
My company uses UUIDs stored in BINARY(16) columns. In our PHP code, libraries sort everything out so that we see the string of the UUID (e.g. `1eaf88f1-dd5f-68e0-950c-080027718adf`). In MySQL, the binary of the field shows by default. I see the option View > Display Binary Data as Hex. While the hex is far more readable than binary, it is still not quite as nice as a properly formatted UUID with hyphens.

It would be nice to have a "Display UUID as String" option, or similar, that uses MySQL's BIN_TO_UUID() function.

<img width="598" alt="Screen Shot 2020-09-16 at 11 02 09 PM" src="https://user-images.githubusercontent.com/3468013/93415174-eaf26080-f870-11ea-8f81-b0bdc4900613.png">

Thank you for picking up Sequel Ace from Sequel Pro. It so nice to have updates again!

**Comment by dinamic** [comment]
It may sound like a workaround, but can't this be achieved with a view?

**Comment by kevindb** [comment]
> It may sound like a workaround, but can't this be achieved with a view?

Using a view would be a workaround, yes, but would have significant overhead in updating the view when the underlying table structure is changed. Not to mention, it doesn't scale well when every table has a uuid column.

With MySQL 8 adding much better support for UUIDs, I thought it would be convenient to be able to see the formatted output in Sequel Ace. If this enhancement/suggestion/request is not appropriate to build into Sequel Ace, that's ok, I understand.

**Comment by dinamic** [comment]
@kevindb we use UUIDv4 in binary form as well. What are you thinking in terms of useability? How should SequelAce know this specific field is an encoded UUIDv4, for example?

**Comment by kevindb** [comment]
> @kevindb we use UUIDv4 in binary form as well. What are you thinking in terms of useability? How should SequelAce know this specific field is an encoded UUIDv4, for example? Where should the option be located at?

@dinamic That is a fine question: _how_ would Sequel Ace know if a BINARY(16) column is a UUID?

In PHP Laravel, it's a strong convention for all primary key integer columns to be named `id`. Similarly, all UUID columns are named `uuid`. From my perspective, in the projects I've worked on, it would work if Sequel Ace treated any BINARY(16) column named `uuid` as a UUID, and display its data using BIN_TO_UUID(). Ideally, this would be an option to turn on in preferences: "Display Binary UUID as formatted".

I recognize that my experience is limited, and I welcome others' feedback if this solution does not work for everyone.

**Comment by paulwis** [comment]
In my opinion such a setting best belongs in the database connection settings. I imagine this would be a global convention per database.

**Comment by kevindb** [comment]
@paulwis Yes, a database connection setting would work great!

**Comment by kevindb** [comment]
I disagree with this closure. It seems to me like there is interest in this feature.

**Comment by dinamic** [comment]
As someone who uses UUIDs on daily basis, it would definitely make my life easier if I didn't have to use our stored procedure to convert UUIDs from binary to string form every time I need one to be copied.

**Comment by franksteinberg** [comment]
Would love to see this!

**Comment by rofthedeep** [comment]
Would love to see this!

**Comment by bfj5889** [comment]
Would also love to see this!

**Comment by Apipa169** [comment]
We would love to see this feature!

**Comment by kevindb** [comment]
I'm still looking forward to this feature.

**Comment by dennisberg91** [comment]
We would love to see this feature!

**Comment by gduh** [comment]
MySQL 8 implements 3 new functions : BIN_TO_UUID(), UUID_TO_BIN() and IS_UUID()
I think, these functions could be used to display a readable UUID. But how to know if the binary data is an UUID ? When the field length is declared to 16 ? Or if the data length equal 16 ? Not so simple. 

Also MariaDB does not implement these functions, so for now it will only work with Mysql > 8.0
It might also be possible to format the data directly in the SA code, so it will not depend on the database engine, but I'm not sure its good option for performance. I think this kind of task must be done by the database engine.

MariaDB 10.7 will introduce a new type : UUID. I think it's a good thing to implement this, it will be easier to use in the future. For now, the 10.7 is in Release Candidate.

@Jason-Morcos What do you think ? Can we try to analyse the code if it's possible ?  And if yes, add an option in the preferences and if set to YES, add the BIN_TO_UUID() function inside the SQL SELECT if the binary (BINARY and VARBINARAY) type is 16 length and only for MySQL engine > 8.0 ?  
If the length of the data contained in the field is less than 16, I don't know what the result might be since I don't have a version of MySQL 8 available to check it.

**Comment by Jason-Morcos** [comment]
> @Jason-Morcos What do you think ? Can we try to analyse the code if it's possible ?  And if yes, add an option in the preferences and if set to YES, add the BIN_TO_UUID() function inside the SQL SELECT if the binary (BINARY and VARBINARAY) type is 16 length and only for MySQL engine > 8.0 ?  
> 
> If the length of the data contained in the field is less than 16, I don't know what the result might be since I don't have a version of MySQL 8 available to check it.

Sounds doable! We may also be able to implement our own bin to uuid function that would work to support older MySQL variants and MariaDB.

**Comment by phit** [comment]
any way to exclude bots from certain issues?

**Comment by luis-** [comment]
Will give this one a shot.

**Comment by luis-** [comment]
Request for comments:

Would a preference like this work for all/most people?
<img width="703" alt="prefs_suggestion_1" src="https://user-images.githubusercontent.com/1121410/151344216-b9f358d1-5828-460e-8f48-1afe6fb9b8b0.png">
Rather than hard coding some naming convention into Sequela Ace, I was thinking we can perhaps supply a comma-separated list of column names? Sequel ace would then apply uuid formatting if the name matches and the column BINARY(16)? I realize that technically you can have commas in a column name though not sure I've ever seen db that actually does that so maybe that's an acceptable limitation in order to try to keep this piece simple. Thoughts/concerns/objections?

**Comment by kevindb** [comment]
> Request for comments:

I love it! It sounds like a pretty perfect way to make it work for any project's naming scheme.

**Comment by ati-pave** [comment]
We would love to see this feature!

**Comment by luis-** [comment]
Finally had a some time to work on my old PR for this again. Here's a little teaser of what I have so far:

![bin(16) as uuid](https://github.com/Sequel-Ace/Sequel-Ace/assets/1121410/b6aec933-105a-4159-bc03-51faa718aac6)

Working so far:
* Support for `BINARY(16) => UUID` only (right-click on non-supported column will not show menu)
* Format selection for column will persist across app re-start (saved to SQLIte db not user defaults)
* Inline editing works

Still working on:
* Broken popup editor 
* Broken table filtering

**Comment by Jason-Morcos** [comment]
This is looking super cool, @luis- !

**Comment by gms8994** [comment]
This would be *huge* for us. Especially if it could be made to work with bundles so that the string version could be copied - though I'd be okay without having that if it were a ridiculous amount of work, as I could still get it easily from the UI.

Is this code to a point that a PR could actually be made to find out if it's mergeable?

**Comment by luis-** [comment]
@gms8994, last night I did a quick test and bundles was using "BLOB" instead of the displayed UUID string but was able to fix some with just a few lines of code. `Bundles > Data Table > Copy > *` seem to work now.

I was away on business the last couple weeks but should be close to ready. After work today I'll rebase on top of latest main to address any merge conflicts and if all goes well I'll get a PR open.
